namespace UI
{
     partial class Form1
     {
          /// <summary>
          /// Required designer variable.
          /// </summary>
          private System.ComponentModel.IContainer components = null;

          /// <summary>
          /// Clean up any resources being used.
          /// </summary>
          /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
          protected override void Dispose(bool disposing)
          {
               if (disposing && (components != null))
               {
                    components.Dispose();
               }
               base.Dispose(disposing);
          }

          #region Windows Form Designer generated code

          /// <summary>
          /// Required method for Designer support - do not modify
          /// the contents of this method with the code editor.
          /// </summary>
          private void InitializeComponent()
          {
               this.groupBox2 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D2 = new NPlot.Windows.PlotSurface2D();
               this.groupBox1 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D1 = new NPlot.Windows.PlotSurface2D();
               this.groupBox3 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D3 = new NPlot.Windows.PlotSurface2D();
               this.g5 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D4 = new NPlot.Windows.PlotSurface2D();
               this.Plot5 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D5 = new NPlot.Windows.PlotSurface2D();
               this.Plot6 = new System.Windows.Forms.GroupBox();
               this.plotSurface2D6 = new NPlot.Windows.PlotSurface2D();
               this.m_runButton = new System.Windows.Forms.Button();
               this.button1 = new System.Windows.Forms.Button();
               this.statusStrip1 = new System.Windows.Forms.StatusStrip();
               this.m_status = new System.Windows.Forms.ToolStripStatusLabel();
               this.m_progBar = new System.Windows.Forms.ProgressBar();
               this.comboBox1 = new System.Windows.Forms.ComboBox();
               this.groupBox2.SuspendLayout();
               this.groupBox1.SuspendLayout();
               this.groupBox3.SuspendLayout();
               this.g5.SuspendLayout();
               this.Plot5.SuspendLayout();
               this.Plot6.SuspendLayout();
               this.statusStrip1.SuspendLayout();
               this.SuspendLayout();
               // 
               // groupBox2
               // 
               this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
               this.groupBox2.Controls.Add(this.plotSurface2D2);
               this.groupBox2.Location = new System.Drawing.Point(403, 12);
               this.groupBox2.Name = "groupBox2";
               this.groupBox2.Size = new System.Drawing.Size(382, 215);
               this.groupBox2.TabIndex = 1;
               this.groupBox2.TabStop = false;
               this.groupBox2.Text = "Plot2";
               // 
               // plotSurface2D2
               // 
               this.plotSurface2D2.AutoScaleAutoGeneratedAxes = false;
               this.plotSurface2D2.AutoScaleTitle = false;
               this.plotSurface2D2.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D2.DateTimeToolTip = false;
               this.plotSurface2D2.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D2.Legend = null;
               this.plotSurface2D2.LegendZOrder = -1;
               this.plotSurface2D2.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D2.Name = "plotSurface2D2";
               this.plotSurface2D2.RightMenu = null;
               this.plotSurface2D2.ShowCoordinates = true;
               this.plotSurface2D2.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D2.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D2.TabIndex = 0;
               this.plotSurface2D2.Text = "plotSurface2D1";
               this.plotSurface2D2.Title = "";
               this.plotSurface2D2.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D2.XAxis1 = null;
               this.plotSurface2D2.XAxis2 = null;
               this.plotSurface2D2.YAxis1 = null;
               this.plotSurface2D2.YAxis2 = null;
               // 
               // groupBox1
               // 
               this.groupBox1.Controls.Add(this.plotSurface2D1);
               this.groupBox1.Location = new System.Drawing.Point(12, 12);
               this.groupBox1.Name = "groupBox1";
               this.groupBox1.Size = new System.Drawing.Size(382, 215);
               this.groupBox1.TabIndex = 2;
               this.groupBox1.TabStop = false;
               this.groupBox1.Text = "Plot 1";
               // 
               // plotSurface2D1
               // 
               this.plotSurface2D1.AutoScaleAutoGeneratedAxes = false;
               this.plotSurface2D1.AutoScaleTitle = false;
               this.plotSurface2D1.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D1.DateTimeToolTip = false;
               this.plotSurface2D1.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D1.Legend = null;
               this.plotSurface2D1.LegendZOrder = -1;
               this.plotSurface2D1.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D1.Name = "plotSurface2D1";
               this.plotSurface2D1.RightMenu = null;
               this.plotSurface2D1.ShowCoordinates = true;
               this.plotSurface2D1.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D1.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D1.TabIndex = 0;
               this.plotSurface2D1.Text = "plotSurface2D6";
               this.plotSurface2D1.Title = "";
               this.plotSurface2D1.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D1.XAxis1 = null;
               this.plotSurface2D1.XAxis2 = null;
               this.plotSurface2D1.YAxis1 = null;
               this.plotSurface2D1.YAxis2 = null;
               // 
               // groupBox3
               // 
               this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
               this.groupBox3.Controls.Add(this.plotSurface2D3);
               this.groupBox3.Location = new System.Drawing.Point(12, 233);
               this.groupBox3.Name = "groupBox3";
               this.groupBox3.Size = new System.Drawing.Size(382, 215);
               this.groupBox3.TabIndex = 2;
               this.groupBox3.TabStop = false;
               this.groupBox3.Text = "Plot3";
               // 
               // plotSurface2D3
               // 
               this.plotSurface2D3.AutoScaleAutoGeneratedAxes = true;
               this.plotSurface2D3.AutoScaleTitle = false;
               this.plotSurface2D3.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D3.DateTimeToolTip = false;
               this.plotSurface2D3.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D3.Legend = null;
               this.plotSurface2D3.LegendZOrder = -1;
               this.plotSurface2D3.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D3.Name = "plotSurface2D3";
               this.plotSurface2D3.RightMenu = null;
               this.plotSurface2D3.ShowCoordinates = true;
               this.plotSurface2D3.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D3.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D3.TabIndex = 0;
               this.plotSurface2D3.Text = "plotSurface2D5";
               this.plotSurface2D3.Title = "";
               this.plotSurface2D3.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D3.XAxis1 = null;
               this.plotSurface2D3.XAxis2 = null;
               this.plotSurface2D3.YAxis1 = null;
               this.plotSurface2D3.YAxis2 = null;
               // 
               // g5
               // 
               this.g5.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
               this.g5.Controls.Add(this.plotSurface2D4);
               this.g5.Location = new System.Drawing.Point(403, 233);
               this.g5.Name = "g5";
               this.g5.Size = new System.Drawing.Size(382, 215);
               this.g5.TabIndex = 2;
               this.g5.TabStop = false;
               this.g5.Text = "Plot4";
               // 
               // plotSurface2D4
               // 
               this.plotSurface2D4.AutoScaleAutoGeneratedAxes = false;
               this.plotSurface2D4.AutoScaleTitle = false;
               this.plotSurface2D4.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D4.DateTimeToolTip = false;
               this.plotSurface2D4.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D4.Legend = null;
               this.plotSurface2D4.LegendZOrder = -1;
               this.plotSurface2D4.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D4.Name = "plotSurface2D4";
               this.plotSurface2D4.RightMenu = null;
               this.plotSurface2D4.ShowCoordinates = true;
               this.plotSurface2D4.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D4.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D4.TabIndex = 0;
               this.plotSurface2D4.Text = "plotSurface2D2";
               this.plotSurface2D4.Title = "";
               this.plotSurface2D4.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D4.XAxis1 = null;
               this.plotSurface2D4.XAxis2 = null;
               this.plotSurface2D4.YAxis1 = null;
               this.plotSurface2D4.YAxis2 = null;
               // 
               // Plot5
               // 
               this.Plot5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
               this.Plot5.Controls.Add(this.plotSurface2D5);
               this.Plot5.Location = new System.Drawing.Point(12, 454);
               this.Plot5.Name = "Plot5";
               this.Plot5.Size = new System.Drawing.Size(382, 215);
               this.Plot5.TabIndex = 3;
               this.Plot5.TabStop = false;
               this.Plot5.Text = "Plot5";
               // 
               // plotSurface2D5
               // 
               this.plotSurface2D5.AutoScaleAutoGeneratedAxes = false;
               this.plotSurface2D5.AutoScaleTitle = false;
               this.plotSurface2D5.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D5.DateTimeToolTip = false;
               this.plotSurface2D5.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D5.Legend = null;
               this.plotSurface2D5.LegendZOrder = -1;
               this.plotSurface2D5.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D5.Name = "plotSurface2D5";
               this.plotSurface2D5.RightMenu = null;
               this.plotSurface2D5.ShowCoordinates = true;
               this.plotSurface2D5.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D5.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D5.TabIndex = 0;
               this.plotSurface2D5.Text = "plotSurface2D4";
               this.plotSurface2D5.Title = "";
               this.plotSurface2D5.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D5.XAxis1 = null;
               this.plotSurface2D5.XAxis2 = null;
               this.plotSurface2D5.YAxis1 = null;
               this.plotSurface2D5.YAxis2 = null;
               // 
               // Plot6
               // 
               this.Plot6.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
               this.Plot6.Controls.Add(this.plotSurface2D6);
               this.Plot6.Location = new System.Drawing.Point(403, 454);
               this.Plot6.Name = "Plot6";
               this.Plot6.Size = new System.Drawing.Size(382, 215);
               this.Plot6.TabIndex = 3;
               this.Plot6.TabStop = false;
               this.Plot6.Text = "Plot6";
               // 
               // plotSurface2D6
               // 
               this.plotSurface2D6.AutoScaleAutoGeneratedAxes = false;
               this.plotSurface2D6.AutoScaleTitle = false;
               this.plotSurface2D6.BackColor = System.Drawing.SystemColors.ControlLightLight;
               this.plotSurface2D6.DateTimeToolTip = false;
               this.plotSurface2D6.Dock = System.Windows.Forms.DockStyle.Fill;
               this.plotSurface2D6.Legend = null;
               this.plotSurface2D6.LegendZOrder = -1;
               this.plotSurface2D6.Location = new System.Drawing.Point(3, 16);
               this.plotSurface2D6.Name = "plotSurface2D6";
               this.plotSurface2D6.RightMenu = null;
               this.plotSurface2D6.ShowCoordinates = true;
               this.plotSurface2D6.Size = new System.Drawing.Size(376, 196);
               this.plotSurface2D6.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
               this.plotSurface2D6.TabIndex = 0;
               this.plotSurface2D6.Text = "plotSurface2D3";
               this.plotSurface2D6.Title = "";
               this.plotSurface2D6.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
               this.plotSurface2D6.XAxis1 = null;
               this.plotSurface2D6.XAxis2 = null;
               this.plotSurface2D6.YAxis1 = null;
               this.plotSurface2D6.YAxis2 = null;
               // 
               // m_runButton
               // 
               this.m_runButton.BackColor = System.Drawing.Color.Lime;
               this.m_runButton.Location = new System.Drawing.Point(569, 682);
               this.m_runButton.Name = "m_runButton";
               this.m_runButton.Size = new System.Drawing.Size(75, 23);
               this.m_runButton.TabIndex = 4;
               this.m_runButton.Text = "Run";
               this.m_runButton.UseVisualStyleBackColor = false;
               this.m_runButton.Click += new System.EventHandler(this.m_runButton_Click);
               // 
               // button1
               // 
               this.button1.Location = new System.Drawing.Point(12, 682);
               this.button1.Name = "button1";
               this.button1.Size = new System.Drawing.Size(144, 23);
               this.button1.TabIndex = 5;
               this.button1.Text = "Generate Random Curves";
               this.button1.UseVisualStyleBackColor = true;
               this.button1.Click += new System.EventHandler(this.button1_Click);
               // 
               // statusStrip1
               // 
               this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.m_status});
               this.statusStrip1.Location = new System.Drawing.Point(0, 708);
               this.statusStrip1.Name = "statusStrip1";
               this.statusStrip1.Size = new System.Drawing.Size(788, 22);
               this.statusStrip1.TabIndex = 6;
               this.statusStrip1.Text = "statusStrip1";
               // 
               // m_status
               // 
               this.m_status.Name = "m_status";
               this.m_status.Size = new System.Drawing.Size(0, 17);
               // 
               // m_progBar
               // 
               this.m_progBar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
               this.m_progBar.Location = new System.Drawing.Point(650, 682);
               this.m_progBar.Name = "m_progBar";
               this.m_progBar.Size = new System.Drawing.Size(126, 23);
               this.m_progBar.TabIndex = 7;
               // 
               // comboBox1
               // 
               this.comboBox1.FormattingEnabled = true;
               this.comboBox1.Items.AddRange(new object[] {
            "Gaussian",
            "Parabolic",
            "Cubic",
            "Line",
            "Cubic/Parabolic"});
               this.comboBox1.Location = new System.Drawing.Point(162, 684);
               this.comboBox1.Name = "comboBox1";
               this.comboBox1.Size = new System.Drawing.Size(121, 21);
               this.comboBox1.TabIndex = 8;
               this.comboBox1.Text = "Gaussian";
               this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
               // 
               // Form1
               // 
               this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
               this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
               this.BackColor = System.Drawing.SystemColors.Control;
               this.ClientSize = new System.Drawing.Size(788, 730);
               this.Controls.Add(this.comboBox1);
               this.Controls.Add(this.m_progBar);
               this.Controls.Add(this.statusStrip1);
               this.Controls.Add(this.button1);
               this.Controls.Add(this.m_runButton);
               this.Controls.Add(this.Plot6);
               this.Controls.Add(this.Plot5);
               this.Controls.Add(this.g5);
               this.Controls.Add(this.groupBox3);
               this.Controls.Add(this.groupBox1);
               this.Controls.Add(this.groupBox2);
               this.MaximumSize = new System.Drawing.Size(804, 768);
               this.MinimumSize = new System.Drawing.Size(804, 768);
               this.Name = "Form1";
               this.Text = "RBF GA Matcher";
               this.groupBox2.ResumeLayout(false);
               this.groupBox1.ResumeLayout(false);
               this.groupBox3.ResumeLayout(false);
               this.g5.ResumeLayout(false);
               this.Plot5.ResumeLayout(false);
               this.Plot6.ResumeLayout(false);
               this.statusStrip1.ResumeLayout(false);
               this.statusStrip1.PerformLayout();
               this.ResumeLayout(false);
               this.PerformLayout();

          }

          #endregion

          private System.Windows.Forms.GroupBox groupBox2;
          private NPlot.Windows.PlotSurface2D plotSurface2D2;
          private System.Windows.Forms.GroupBox groupBox1;
          private NPlot.Windows.PlotSurface2D plotSurface2D1;
          private System.Windows.Forms.GroupBox groupBox3;
          private NPlot.Windows.PlotSurface2D plotSurface2D3;
          private System.Windows.Forms.GroupBox g5;
          private NPlot.Windows.PlotSurface2D plotSurface2D4;
          private System.Windows.Forms.GroupBox Plot5;
          private NPlot.Windows.PlotSurface2D plotSurface2D5;
          private System.Windows.Forms.GroupBox Plot6;
          private NPlot.Windows.PlotSurface2D plotSurface2D6;
          private System.Windows.Forms.Button m_runButton;
          private System.Windows.Forms.Button button1;
          private System.Windows.Forms.StatusStrip statusStrip1;
          private System.Windows.Forms.ToolStripStatusLabel m_status;
          private System.Windows.Forms.ProgressBar m_progBar;
          private System.Windows.Forms.ComboBox comboBox1;

     }
}

