namespace NsNodeControls
{
	partial class NsNodePlot
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.splitContainer1 = new System.Windows.Forms.SplitContainer();
			this.label2 = new System.Windows.Forms.Label();
			this.label1 = new System.Windows.Forms.Label();
			this.comboY = new System.Windows.Forms.ComboBox();
			this.comboX = new System.Windows.Forms.ComboBox();
			this.plotSurface2D1 = new NPlot.Windows.PlotSurface2D();
			this.plotBtn = new System.Windows.Forms.Button();
			this.nsAttributeGridView1 = new NsNodeControls.NsAttributeGridView();
			this.splitContainer1.Panel1.SuspendLayout();
			this.splitContainer1.Panel2.SuspendLayout();
			this.splitContainer1.SuspendLayout();
			this.SuspendLayout();
			// 
			// splitContainer1
			// 
			this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.splitContainer1.Location = new System.Drawing.Point(0, 0);
			this.splitContainer1.Name = "splitContainer1";
			// 
			// splitContainer1.Panel1
			// 
			this.splitContainer1.Panel1.Controls.Add(this.nsAttributeGridView1);
			// 
			// splitContainer1.Panel2
			// 
			this.splitContainer1.Panel2.Controls.Add(this.plotBtn);
			this.splitContainer1.Panel2.Controls.Add(this.label2);
			this.splitContainer1.Panel2.Controls.Add(this.label1);
			this.splitContainer1.Panel2.Controls.Add(this.comboY);
			this.splitContainer1.Panel2.Controls.Add(this.comboX);
			this.splitContainer1.Panel2.Controls.Add(this.plotSurface2D1);
			this.splitContainer1.Size = new System.Drawing.Size(666, 666);
			this.splitContainer1.SplitterDistance = 240;
			this.splitContainer1.TabIndex = 1;
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(8, 37);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(12, 13);
			this.label2.TabIndex = 2;
			this.label2.Text = "y";
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(8, 10);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(12, 13);
			this.label1.TabIndex = 2;
			this.label1.Text = "x";
			// 
			// comboY
			// 
			this.comboY.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
					  | System.Windows.Forms.AnchorStyles.Right)));
			this.comboY.FormattingEnabled = true;
			this.comboY.Location = new System.Drawing.Point(26, 34);
			this.comboY.Name = "comboY";
			this.comboY.Size = new System.Drawing.Size(312, 21);
			this.comboY.TabIndex = 1;
			this.comboY.SelectedIndexChanged += new System.EventHandler(this.combo_SelectedIndexChanged);
			// 
			// comboX
			// 
			this.comboX.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
					  | System.Windows.Forms.AnchorStyles.Right)));
			this.comboX.FormattingEnabled = true;
			this.comboX.Location = new System.Drawing.Point(26, 7);
			this.comboX.Name = "comboX";
			this.comboX.Size = new System.Drawing.Size(312, 21);
			this.comboX.TabIndex = 1;
			this.comboX.SelectedIndexChanged += new System.EventHandler(this.combo_SelectedIndexChanged);
			// 
			// plotSurface2D1
			// 
			this.plotSurface2D1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
					  | System.Windows.Forms.AnchorStyles.Left)
					  | System.Windows.Forms.AnchorStyles.Right)));
			this.plotSurface2D1.AutoScaleAutoGeneratedAxes = false;
			this.plotSurface2D1.AutoScaleTitle = false;
			this.plotSurface2D1.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plotSurface2D1.DateTimeToolTip = false;
			this.plotSurface2D1.Legend = null;
			this.plotSurface2D1.LegendZOrder = -1;
			this.plotSurface2D1.Location = new System.Drawing.Point(2, 61);
			this.plotSurface2D1.Name = "plotSurface2D1";
			this.plotSurface2D1.RightMenu = null;
			this.plotSurface2D1.ShowCoordinates = true;
			this.plotSurface2D1.Size = new System.Drawing.Size(420, 605);
			this.plotSurface2D1.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.plotSurface2D1.TabIndex = 0;
			this.plotSurface2D1.Text = "plotSurface2D1";
			this.plotSurface2D1.Title = "";
			this.plotSurface2D1.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plotSurface2D1.XAxis1 = null;
			this.plotSurface2D1.XAxis2 = null;
			this.plotSurface2D1.YAxis1 = null;
			this.plotSurface2D1.YAxis2 = null;
			// 
			// plotBtn
			// 
			this.plotBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.plotBtn.Location = new System.Drawing.Point(344, 7);
			this.plotBtn.Name = "plotBtn";
			this.plotBtn.Size = new System.Drawing.Size(75, 48);
			this.plotBtn.TabIndex = 3;
			this.plotBtn.Text = "Plot!";
			this.plotBtn.UseVisualStyleBackColor = true;
			this.plotBtn.Click += new System.EventHandler(this.plotBtn_Click);
			// 
			// nsAttributeGridView1
			// 
			this.nsAttributeGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.nsAttributeGridView1.Location = new System.Drawing.Point(0, 0);
			this.nsAttributeGridView1.Name = "nsAttributeGridView1";
			this.nsAttributeGridView1.Node = null;
			this.nsAttributeGridView1.Size = new System.Drawing.Size(240, 666);
			this.nsAttributeGridView1.TabIndex = 0;
			// 
			// NsNodePlot
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.splitContainer1);
			this.Name = "NsNodePlot";
			this.Size = new System.Drawing.Size(666, 666);
			this.splitContainer1.Panel1.ResumeLayout(false);
			this.splitContainer1.Panel2.ResumeLayout(false);
			this.splitContainer1.Panel2.PerformLayout();
			this.splitContainer1.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion

		private NsAttributeGridView nsAttributeGridView1;
		private System.Windows.Forms.SplitContainer splitContainer1;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.ComboBox comboY;
		private System.Windows.Forms.ComboBox comboX;
		private NPlot.Windows.PlotSurface2D plotSurface2D1;
		private System.Windows.Forms.Button plotBtn;
	}
}
